name: Lint CI
on:
  pull_request:
  push:
    branches: [ master ]
    paths:
      - '**.py'
jobs:
    python-lint:
      name: Check Python code
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pylint
        - name: Lint with pylint
          run: pylint **/*.py
